### ISSUE TITLE
Warning using the disabled and using ngModel on the same form field as formControl

### ISSUE THREAD

**Issue by LauraNavarroGalvan** [malothnaresh/mat-select-autocomplete#4] opened 2019-07-18 22:56 UTC
I'm trying to use the implementation for Angular 7, but I get these warnings and I'm not using disable or ngmodel
![image](https://user-images.githubusercontent.com/39338495/61497536-66aeff80-a985-11e9-9b44-a943f11ebd4d.png)

**Comment by malothnaresh** [comment] 2019-07-21 14:03
Not able to reproduce. Could you please check with your implementation or provide steps to reproduce ?

**Comment by LauraNavarroGalvan** [comment] 2019-07-21 22:20
you can see the same warnings in the demo console
https://stackblitz.com/edit/mat-select-autocomplete

**Comment by malothnaresh** [comment] 2019-07-23 07:16
Release 1.2.4 has fixed first warning. Would come up with solution for second warning later.

**Comment by malothnaresh** [comment] 2019-09-17 09:38
Partial fix committed. The library does not support another part of it.

**Closed by malothnaresh** 2019-09-17 09:38 UTC

**Comment by bachrc** [comment] 2020-08-10 19:29
This issue is still here :/
